server:
    port: 2000

logging:
  level:
    org.springframework.web: INFO
    com.springboot.study.security_demo.mapper: DEBUG

spring:
    # mysql 的数据库配置
    datasource:
        url: jdbc:mysql://localhost:3306/mydb?characterEncoding=utf-8&amp;autoReconnect=true
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            auto-commit: true
            connection-test-query: SELECT 1
            connection-timeout: 30000
            idle-timeout: 30000
            max-lifetime: 1800000
            maximum-pool-size: 15
            minimum-idle: 5
            pool-name: DatebookHikariCP
    # redis 配置
    redis:
        database: 0              # Redis数据库索引（默认为0）
        host: 127.0.0.1          # Redis服务器地址
        password: xs0529         # Redis服务器连接密码（默认为空）
        port: 6379               # Redis服务器连接端口
        timeout: 5000            # 连接超时时间（毫秒）
        jedis:
            pool:
                max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
                max-idle: 8      # 连接池中的最大空闲连接
                max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
                min-idle: 0      # 连接池中的最小空闲连接
    thymeleaf:
        cache: false
    # 静态资源路径
    resources:
        static-locations: classpath:static/,file:static/
    flyway:
        enabled: false
        encoding: utf-8
        validate-on-migrate: true
        baseline-on-migrate: true
mybatis-plus:
  mapper-locations: classpath*:**/mapper/xml/*.xml
  global-config:
      db-config:
          id-type: auto

yanzhi: jkasdjfljdfiojk

